name: Auto Tag, Branch and Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # 支持手动触发
  
permissions:
  contents: write

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Log in to aliyunHub
        run: docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build amd64
        run: |
          docker build --no-cache -t icepage/aujc .
          docker push icepage/aujc:amd64
          docker tag icepage/aujc:amd64 registry.cn-hangzhou.aliyuncs.com/icepage/aujc:amd64
          docker push registry.cn-hangzhou.aliyuncs.com/icepage/aujc:amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Log in to aliyunHub
        run: docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build arm64
        run: |
          docker build --no-cache -t icepage/aujc .
          docker push icepage/aujc:arm64
          docker tag icepage/aujc:arm64 registry.cn-hangzhou.aliyuncs.com/icepage/aujc:arm64
          docker push registry.cn-hangzhou.aliyuncs.com/icepage/aujc:arm64

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to aliyunHub
        run: docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push Multi-arch Manifest
        run: |
          docker manifest create icepage/aujc:latest \
            --amend icepage/aujc:amd64 \
            --amend icepage/aujc:arm64
          docker manifest push icepage/aujc:latest
          docker manifest create registry.cn-hangzhou.aliyuncs.com/icepage/aujc:latest \
            --amend registry.cn-hangzhou.aliyuncs.com/icepage/aujc:amd64 \
            --amend registry.cn-hangzhou.aliyuncs.com/icepage/aujc:arm64
          docker manifest push registry.cn-hangzhou.aliyuncs.com/icepage/aujc:latest